name: "Build and Deploy to Heroku"

on:
  push:
    branches:
      - main
        
env:
  HEROKU_APP_NAME: "school-quiz-tg-bot"
  HEROKU_APP_PROCESS_NAME: "bot"
  HEROKU_USERNAME: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  COSMOSDB_ACCOUNT_KEY: ${{ secrets.COSMOSDB_ACCOUNT_KEY }}
  COSMOSDB_ACCOUNT_URI: ${{ secrets.COSMOSDB_ACCOUNT_URI }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          
jobs:
  deploy:
    name: "Build and Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Login to Heroku Container Registry"
        run: |
          docker login --username=${{ env.HEROKU_USERNAME }} --password=${{ env.HEROKU_API_KEY }} registry.heroku.com

      - name: "Build Docker image"
        run: |
          docker build \
          -t registry.heroku.com/${{ env.HEROKU_APP_NAME }}/${{ env.HEROKU_APP_PROCESS_NAME }} \
          -f src/apps/quizBot/Dockerfile  \
          --platform linux/amd64 \
          --build-arg COSMOSDB_ACCOUNT_KEY=${{ env.COSMOSDB_ACCOUNT_KEY }} \
          --build-arg COSMOSDB_ACCOUNT_URI=${{ env.COSMOSDB_ACCOUNT_URI }} \
          --build-arg TELEGRAM_TOKEN=${{ env.TELEGRAM_TOKEN }} \
          ./

      - name: "Push Docker image to Heroku"
        run: |
          docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/${{ env.HEROKU_APP_PROCESS_NAME }}

      - name: Release the application on Heroku
        run: |
          heroku container:release ${{ env.HEROKU_APP_PROCESS_NAME }} --app ${{ env.HEROKU_APP_NAME }}
